version: '3'
services:
  app:
    image: redgamerr/zeta-panel
    environment:
      TOKEN: 6186246611:AAHtikQ5N_KaYHOdgTsjxnJKt_KX4eFJIKs
    volumes:
      - database:/app/instance
      - database:/app/migration
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
volumes:
  database: