version: '3'
services:
  app:
    image: redgamerr/zeta-panel
    environment:
      SQLALCHEMY_DATABASE_URI: sqlite:////data/app.db
      TOKEN: 6186246611:AAHtikQ5N_KaYHOdgTsjxnJKt_KX4eFJIKs
    volumes:
      - ./data:/data
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/cert.pem:/etc/nginx/ssl/cert.pem
      - ./data/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped