version: '3'
services:
  app:
    image: redgamerr/zetapanel
    environment:
      TOKEN: TOKEN
    volumes:
      - database:/app/instance
      - migrations:/app/migrations
      - upload:/app/app/static/upload
      - logs:/app/logs
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
volumes:
  database:
  migrations:
  upload:
  logs: